### ISSUE TITLE
Document wofost model output variables

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/nevergrad#35]
## Context
We need to understand clearly what is the meaning of each variable output by  the WOFOST model of Allard

Here is the list of variables:
- [ ] DVS
- [ ] LAI
- [ ] TAGP
- [ ] TWSO
- [ ] TWLV
- [ ] TWST
- [ ] TWRT
- [ ] TRA
- [ ] RD
- [ ] SM
- [ ] WWLOW

## Reference
![image](https://user-images.githubusercontent.com/26568112/182252323-c45b208b-df71-49c5-86f3-f1c60c31c5cb.png)

@Ethel2003 I need you on this one

**Comment by akouete-kpakpo** [comment]
What I infer with tuto notebooks:

- LAI: Leaf Area Index
- TAGP: total biomass
- TWSO.: Yield
- SM: root zone soil moisture
- DVS: development stage

**Comment by Ethel2003** [comment]
- RD: Depth of actual root zone (cm)
- TWLV: Total dry weight of leaves (dead and living) (kg•ha-1)
- TWST:Total dry weight of stems (dead and living) (kg•ha-1)
- TWRT: Total dry weight of roots
- TRA: Transpiration rate (mm•d-1)
- WWLOW: Amount of water in cm available in the rooted zone (variable W) plus the lower (unrooted) zone (variable WLOW)

More explicitly, the definition of the variables is :

• DVS: the crop development stage. A dimensionless variable that defines the phenological
development of the crop. DVS values range from -0.1 at sowing, to 0.0 at emergence, 1.0 at
flowering and 2.0 at physiological maturity. DVS values can be easily compared between years
in order to determine if the development cycle of crops is slower or faster than the long-term
average or any previous year. A footnote in interpreting the crop development stage is that the
phenological model used by WOFOST is a typical model for cereals. All other crops are forced
into this model. For cereals DVS=1.0 (flowering) starts the reproductive phase and thus the
filling of the storage organs (grains). For non-cereals this implies that DVS=1 also corresponds
to the start of yield formation. For example, DVS=1 for potatoes means the start of tuber
bulking instead of flowering because flowering in potatoes has little agronomic relevance. Also
DVS=2 represents physiological maturity. However, for certain crops (e.g. sugar beet) there is
no true physiological maturity and the crop is harvested at a given date rather than at maturity.
For such crops, DVS=2 has no true meaning and its value can either be smaller or larger than 2
at harvest. Given that the results in Table 1 are for a cereal crop (a spring wheat), the
simulation ends neatly with DVS=2. Finally, it should be realized that the DVS is an important
variable and nearly all other processes in WOFOST depend on it. Therefore, it is critical that the
phenological development is well calibrated and correctly simulated.

• LAI: the leaf area index of the crop. It is a dimensionless variable that defines the one-sided
area of living (green) leaves per area of ground surface. Table 1 represents the last 5 days of
the simulation and the crop canopy has fully senesced with LAI=0. Because LAI=0, there is no
photosynthesis anymore and therefore the columns related to biomass (TAGP, TWSO, TWLV,
TWST, TWRT) do not increase anymore and the crop transpiration (TRA) is zero as well.

• TAGP: the Total Above-Ground Production represents the total above-ground biomass that the
crop has produced as dry weight in kg/ha. TAGP is the sum of the individual above-ground plant
organs, so it holds that TAGP =TWSO + TWLV + TWST.

• TWSO: the Total Weight Storage Organs represents the harvestable product (the yield) of the
crop. For cereals these are grains, for potato this represents the tubers, for soybean the beans,
etc. It is always represented as dry weight in kg/ha. The latter means that there will be a
difference between harvested yield and simulated yield due to the difference between dry weight
and fresh weight. The magnitude of this difference depends mainly on the water content in the
final yield. For example, cereals only have 10-15% water content while potatoes and sugar beet
contain a lot of water and therefore there is a large difference between fresh weight and dry
weight estimated by WOFOST.

• TWLV: the Total Weight Leaves represents the cumulative amount of leaf biomass that has been
formed during the growth cycle. Internally, TWLV is partitioned into dead and living leaf biomass
where the latter is used to estimate the crop LAI. The model output in Table 1 demonstrates that
LAI=0 which implies that there are no more living (green) leaves and all leaf biomass is in the
dead pool.

• TWST: the Total Weight Stems represents the amount of biomass that is represented by the
stems of the crop as dry weight in kg/ha. The amount of stem material varies a lot between crop
species and also between cultivars.

• TWRT: the Total Weight Roots represents the amount of biomass that is represented by the
roots of the crop as dry weight in kg/ha. The partitioning schema of WOFOST first divides
(partitions) the assimilates between roots (below-ground) and shoots (above-ground). Next, it partitions between the above ground plant organs (leaves, stems, storage). Root biomass is
often difficult to validate because observations of plant root biomass are difficult to obtain. Note
that in WOFOST there is no relationship between root biomass and root depth.

• TRA: The crop transpiration (excluding soil evaporation) in cm/day which represents the amount
of water that the crop obtains from the soil and which is transpired through its leaves.

• RD: The crop rooting depth in cm. As the example relates to the end of the season RD
represents the depth to which the roots are able to penetrate the soil. It is computed as the
minimum between maximum crop rootable depth (a crop parameter) and the maximum soil
rootable depth (as soil parameters). Table 1 represents the results of a spring wheat crop which
has maximum crop rootable depth of around 125 cm. The current results are thus for a soil
where rooting depth is limited to 60 cm.

• SM: In this case it represents the root zone soil moisture as a volumetric fraction. A completely
dry soil has value zero while the maximum value pertains to a fully saturated soil (soil
dependent but usually around 0.4 for mineral soils). However, its interpretation may depend on
the type of soil moisture balance that is used. Also the naming of the variable can differ between
the model configurations. In this case, the results demonstrate that SM is a constant value of
0.3175. This is because we are running for a potential production situation where soil moisture is
kept constant and sufficiently high in order to be non-limiting for growth.

• WWLOW: this represents the amount of water in cm available in the rooted zone (variable W)
plus the lower (unrooted) zone (variable WLOW). In the current model run, its value equals
None which means that the value does not exist. This is because the variable does not exist in a
potential production simulation.

**Comment by akouete-kpakpo** [comment]
@Ethel2003 wow! Excellent work! I'm impressed. 

Could you share the reference you used?

Could you add it in the Wiki?

Then we wan close the issue.

**Comment by Ethel2003** [comment]
The reference that I used is the book  "A gentle introduction to WOFOST".
